#!/usr/bin/env python 
# -*- coding:utf-8 -*-

import os
import time
print(os.getcwd())
print(os.chdir(".."))
print(os.curdir)
print(os.pardir)
print(os.makedirs(r'W:\a\b\c'))
print(os.removedirs(r'W:\a\b\c'))
print(os.mkdir(r'W:\a'))
print(os.rmdir(r'W:\a'))
print(os.listdir(os.pardir))
print(os.remove())
print(os.rename("oldname","newname"))
print(os.stat('path/filename'))
print(os.sep)
print(os.linesep)
print(os.pathsep)
print(os.name)
print(os.system("bash command"))
print(os.environ)
print(os.path.abspath(r'C:\Users\djn1\Desktop'))
print(os.path.split(r'C:\Users\djn1\Desktop'))
print(os.path.dirname(r'C:\Users\djn1\Desktop'))
print(os.path.basename(r'C:\Users\djn1\Desktop'))
print(os.path.exists(r'C:\Users\djn1\Desktop'))
print(os.path.isabs(r'C:\Users\djn1\Desktop'))
print(os.path.isfile(r'C:\Users\djn1\Desktop'))
print(os.path.isdir(r'C:\Users\djn1\Desktop'))
print(os.path.join(r'C:\Users\djn1\Desktop\tx.txt'))
print(os.path.getatime(r'C:\Users\djn1\Desktop\tx.txt'))
print(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(os.path.getatime(r'C:\Users\djn1\Desktop\tx.txt'))))